services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true

  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: ./docker/db/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: volume
        source: db_data
        target: /var/lib/mysql
    ports:
      - 13306:3306

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - type: bind
        source: ./openapi.yml
        target: /openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml

volumes:
  db_data:
    driver: local