/*
 * memo-go
 *
 * メモのCRUD用API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	DeleteMemo(http.ResponseWriter, *http.Request)
	GetMemo(http.ResponseWriter, *http.Request)
	GetMemos(http.ResponseWriter, *http.Request)
	PostMemo(http.ResponseWriter, *http.Request)
	PostMemos(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	DeleteMemo(context.Context, int32) (ImplResponse, error)
	GetMemo(context.Context, int32) (ImplResponse, error)
	GetMemos(context.Context) (ImplResponse, error)
	PostMemo(context.Context, int32, InlineObject1) (ImplResponse, error)
	PostMemos(context.Context, InlineObject) (ImplResponse, error)
}
