/*
 * memo-go
 *
 * メモのCRUD用API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DeleteMemo - メモの削除
func (s *DefaultApiService) DeleteMemo(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update DeleteMemo with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2004{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2004{}), nil

	//TODO: Uncomment the next line to return response Response(404, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(404, InlineResponse500{}), nil

	//TODO: Uncomment the next line to return response Response(500, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(500, InlineResponse500{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteMemo method not implemented")
}

// GetMemo - メモの詳細
func (s *DefaultApiService) GetMemo(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update GetMemo with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2002{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2002{}), nil

	//TODO: Uncomment the next line to return response Response(404, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(404, InlineResponse500{}), nil

	//TODO: Uncomment the next line to return response Response(500, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(500, InlineResponse500{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMemo method not implemented")
}

// GetMemos - メモの一覧取得
func (s *DefaultApiService) GetMemos(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetMemos with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []InlineResponse200{}) or use other options such as http.Ok ...
	//return Response(200, []InlineResponse200{}), nil

	//TODO: Uncomment the next line to return response Response(500, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(500, InlineResponse500{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMemos method not implemented")
}

// PostMemo - メモの更新
func (s *DefaultApiService) PostMemo(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update PostMemo with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2003{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2003{}), nil

	//TODO: Uncomment the next line to return response Response(404, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(404, InlineResponse500{}), nil

	//TODO: Uncomment the next line to return response Response(500, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(500, InlineResponse500{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostMemo method not implemented")
}

// PostMemos - メモの作成
func (s *DefaultApiService) PostMemos(ctx context.Context, inlineObject InlineObject) (ImplResponse, error) {
	// TODO - update PostMemos with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2001{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2001{}), nil

	//TODO: Uncomment the next line to return response Response(400, InlineResponse400{}) or use other options such as http.Ok ...
	//return Response(400, InlineResponse400{}), nil

	//TODO: Uncomment the next line to return response Response(500, InlineResponse500{}) or use other options such as http.Ok ...
	//return Response(500, InlineResponse500{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostMemos method not implemented")
}
