/*
 * memo-go
 *
 * メモのCRUD用API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2004 struct {

	// 削除成功メッセージ
	Message string `json:"message"`
}

// AssertInlineResponse2004Required checks if the required fields are not zero-ed
func AssertInlineResponse2004Required(obj InlineResponse2004) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseInlineResponse2004Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2004 (e.g. [][]InlineResponse2004), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2004Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2004, ok := obj.(InlineResponse2004)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2004Required(aInlineResponse2004)
	})
}
