/*
 * memo-go
 *
 * メモのCRUD用API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse500 struct {

	// エラーメッセージ
	Message string `json:"message"`
}

// AssertInlineResponse500Required checks if the required fields are not zero-ed
func AssertInlineResponse500Required(obj InlineResponse500) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseInlineResponse500Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse500 (e.g. [][]InlineResponse500), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse500Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse500, ok := obj.(InlineResponse500)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse500Required(aInlineResponse500)
	})
}
