/*
 * memo-go
 *
 * メモのCRUD用API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2003 struct {

	// 更新成功メッセージ
	Message string `json:"message"`
}

// AssertInlineResponse2003Required checks if the required fields are not zero-ed
func AssertInlineResponse2003Required(obj InlineResponse2003) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseInlineResponse2003Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineResponse2003 (e.g. [][]InlineResponse2003), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineResponse2003Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineResponse2003, ok := obj.(InlineResponse2003)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineResponse2003Required(aInlineResponse2003)
	})
}
